### ISSUE TITLE
Magnetic field visualization for Earth cuts off in wide window

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/faradays-electromagnetic-lab#110]
See screenshot below. This only occurs when the Earth view is selected and the window is stretched horizontally. Could this be caused by the magnetic field being rotated, and deriving its values from a non-square matrix?

<img width="1716" alt="Screen Shot 2024-03-19 at 6 34 46 PM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/654c642b-5aeb-44b5-bd82-977d3218862b">

Discovered as part of https://github.com/phetsims/faradays-electromagnetic-lab/issues/103

**Comment by pixelzoom** [comment]
I'm not sure how to address this issue.

Due to the shape of the field for a cylindrical magnet, that's what's going to happen when you rotate the magnet so that it's perpendicular to the longer dimension of the browser window.  Turn on the "Field Lines" visualizion in the Faraday's Law sim, and imagine what that would look like if the magnet were rotated 90 degrees.

Or are you saying that the field is correct, but that parts of the field are not visible because the browser window is not large enough in the vertical dimension? What can we do about that?

**Comment by pixelzoom** [comment]
If I make the browser window narrow and tall, so that the magnet is now parallel to the longer dimension of the browser window, then I can see more of the B-field.

<img width="588" alt="screenshot_3094" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/ed920347-c7dd-4529-a396-783dd8044520">

**Comment by pixelzoom** [comment]
@matthew-blackman What are you seeing here that is incorrect or unexpected? Would you like to discuss on Zoom?

**Comment by matthew-blackman** [comment]
The issue is that a student could get the impression that the B-field is finite and limited to a specified region, rather than gradually tapering off as distance increases. Seeing the compass needles go from a medium-opacity to zero in one column gives the impression that there is a maximum range of the B-field.

<img width="784" alt="Screen Shot 2024-03-21 at 9 16 00 AM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/9688efda-314b-43f9-9a49-67d5097d2904">

Also happy to discuss over Zoom.

**Comment by pixelzoom** [comment]
Thanks, now I understand the problem that you're reporting.  In https://github.com/phetsims/faradays-electromagnetic-lab/issues/110#issue-2196169340, I thought you were referring to "cut off" in th vertical dimension.  https://github.com/phetsims/faradays-electromagnetic-lab/issues/110#issuecomment-2012273436 clarifies that you're referring to the horizontal dinmensions.

I don't see this problem in the Java version (screenshot below) so it's probably a porting regression. I'll investigate.
<img width="1266" alt="screenshot_3101" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/871515c5-c05f-4bad-8893-fba711397c90">

**Comment by pixelzoom** [comment]
@matthew-blackman The reason that you're seeing this problem is that you ran with ?dev, and you changed the Field Scale (in Developer accordion box) to its maximum.   The sim is fine with it's default Field Scale, see screenshot below.  Please close unless there's something I'm missing here.

<img width="1056" alt="screenshot_3102" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/8b6c8b5c-03b4-439b-bef3-39ad6afba7c3">

**Comment by matthew-blackman** [comment]
Tested and confirmed that this is not an issue with the default FieldNode opacity scaling. It is worth noting that if the FieldNode opacity scaling or the strength of the B-field source were changed in the future, this could become noticeable. I agree that it's not a problem with the sim in its current state. Closing.

**Comment by pixelzoom** [comment]
>  It is worth noting that if the FieldNode opacity scaling or the strength of the B-field source were changed in the future, this could become noticeable. I agree that it's not a problem with the sim in its current state. 

The same can be said for all of the Developer controls.  Changing any of those controls risks introducing undesirable behavior, and you need to test thoroughly. 

For fieldScaleProperty specifically, I added this "Caution" to the doc in Magnet.ts:

```ts
...
  // field appear to drop off more rapidly. Larger values make the field appear to drop off more slowly. Caution: If
  // you make the value too large for the bar magnet, the field will end abruptly at the ends of the MathCAD data sets.
  public readonly fieldScaleProperty: NumberProperty;
```
