### ISSUE TITLE
Induced current ignores resistance of pickup coil

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/faradays-electromagnetic-lab#119]
This was discovered as part of #103. As described in #118, the sim is using current and voltage interchangeably, ignoring the resistance of the pickup coil. This is leading to behavior, such as the recording shown below in which the pickup coil behaves as if it has a constant resistance.

https://github.com/phetsims/faradays-electromagnetic-lab/assets/108756567/514429b1-e7a7-4aa3-b4a0-1580a0a5a263

Is the sim model treating the pickup coil as if it has a constant resistance, even when the number of loops is changed? If so, please document this and explain under which conditions this would be a reasonable approximation. This is a concept that many students (and teachers) struggle with, so the behavior should be fully described if there are assumptions being applied.

**Comment by matthew-blackman** [comment]
Note: This model makes sense if the resistance of the wires themselves are negligible, and the entire resistance of the pickup coil is being concentrated in the bulb/resistor/non-wire parts. A line of documentation about this where it is implemented, as well as a note in model.md, would be helpful to make this more explicit.

**Comment by pixelzoom** [comment]
model.md explicitly says that we are not modeling resistance:

> ### Electromagnet
> ... Note that there is no model of resistance for the coil or voltage source.

@arouinfar How do you want to proceed?

**Comment by pixelzoom** [comment]
Discussed with @arouinfar.  Adding resistance and current to the model is not something we want to do.  

Issues #117, #118, and #119 all feel like variations of the same issues, caused by the same misunderstanding that we are attempting to model current and resistance.  That is not the case. This model operates entirely on **induced EMF**. The induced EMF (normalized to [-1,1]) drives the light bulb, voltmeter, and electrons.  When we speak of "current in the coil" or "currrent source for the electromagnet", that is an illusion -- **there is no current and and no resistance in the model**.  And indeed, that is physically correct, nor is it intended to be.  It's a Hollywood model that is indended to provide the behavior of a physical model, absent the effect of resistance.

In #130 we are considering renaming `currentAmplitudeProperty` to something else. Despite the fact that it's well-documented as "this is not current", REVIEW comments, #118, and #119 make it clear that the reviewers think it's current.

@matthew-blackman @samreid Where to next on this issue?

**Comment by pixelzoom** [comment]
Discussed with @matthew-blackman and @samreid.  The resolution for this issue is to improve the documentation in model.md.  @matthew-blackman will take a stab at that in https://github.com/phetsims/faradays-electromagnetic-lab/issues/70, and @arouinfar and I will review.

@matthew-blackman Anything else here? If not, feel free to close.

**Comment by matthew-blackman** [comment]
Continuing remaining work in #70. Closing.
