### ISSUE TITLE
Should we create DOT/Range.times or equivalent?

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#123]
Discovered in #103, there at least 4 occurrences in the simulation where a Range is used to create a scaled/transformed Range. This is leading to a little bit of duplicated code and an opportunity to add a new feature to Range.  Range already has `shifted` so there is a precedent for this kind of method.

For instance: 

```ts
const MAX_VOLTAGE_RANGE = new Range( ( MAX_VOLTAGE_PERCENT_RANGE.min / 100 ) * MAX_VOLTAGE, ( MAX_VOLTAGE_PERCENT_RANGE.max / 100 ) * MAX_VOLTAGE );
```

could become something like:

```ts
const MAX_VOLTAGE_RANGE = MAX_VOLTAGE_PERCENT_RANGE.times( MAX_VOLTAGE / 100 );
```

**Comment by pixelzoom** [comment]
I see 3 places where a Range `times` method could be used.

I don't see how Range `times` could be used here without creating an intermediate Range instance:

```ts
    // REVIEW - Consider a Range method for this, see https://github.com/phetsims/faradays-electromagnetic-lab/issues/123
    this.loopRadiusRange = new Range(
      Math.sqrt( ( this.loopAreaPercentProperty.range.min / 100 ) * options.maxLoopArea / Math.PI ),
      Math.sqrt( ( this.loopAreaPercentProperty.range.max / 100 ) * options.maxLoopArea / Math.PI )
    );
```

**Comment by samreid** [comment]
Good point! We didn't see the `Math.sqrt` in that one.

**Comment by pixelzoom** [comment]
For 3 of the 4 places where I could use Range `times`, I ended up replacing the computed values with literal values, because they did not need to be computed.  

For the `loopRadiusRange` case above, I added a comment, but didn't otherwise change it.  Changing it obfuscates conversion from area to radius: r = sqrt( A / PI ).

Here's the implementation of Range `times` -- which I did not add, because I didn't need it, and don't have time to add to RangeTests.ts:

```ts
  /**
   * Returns new Range instance, created by scaling this Range's min and max by the provided scalar value.
   */
  public times( scalar: number ): Range {
    // eslint-disable-next-line no-html-constructors
    return new Range( scalar * this.min, scalar * this.max );
  }
```
