### ISSUE TITLE
Remove unused parameter scale = 1

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#129]
During review #103, we observed an unused parameter declaration:

```ts
  /**
   * Creates an icon for the AC power supply. This is the universal symbol for AC power.
   */
  public static createIcon( scale = 1 ): Node {
```

**Comment by pixelzoom** [comment]
Icon scales have changed a few times over the course of implementation.  And other `createIcon` methods have a `scale` parameter.  So rather than remove the parameter for `ACPowerSupplyNode.createIcon`, it seems better to properly propagate its value to the icon.  This has been done in https://github.com/phetsims/faradays-electromagnetic-lab/commit/fe61f1cc3354282eea491cb2c0b7d4c3f4a53cce.  Closing.
