### ISSUE TITLE
Unexpected low performance when dragging the FieldMeterNode

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#142]
During code review #103, we observed an unexpectedly low frame rate while dragging the FieldMeterNode.  Test machine:
MacBook Air M1
macOS 14.2.1 
Chrome Version 123.0.6312.59

We found much of the time was being spent in assertions for the scene graph. However, when running without assertions, we saw an unexpectedly high percent time (9%) spent in updating the FieldMeterNode readouts:

<img width="2560" alt="image" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/679486/c16b64ee-70ea-449e-9cda-ec81a8ee1544">

We found that FieldMeterNode is using a new scenery-phet component called StringDisplay which was introduced in https://github.com/phetsims/faradays-electromagnetic-lab/issues/68. StringDisplay is hard-coded to use RichText, which likely explains some of the performance deficit. Therefore we wanted to check whether RichText was necessary here.

**Comment by pixelzoom** [comment]
First, I'll note that this sim was performance tested on Chromebook and older iPad, and there was no problem noted with responsiveness.  That said...

Here's the field meter for the 2 choices of magnetic units:

<img width="203" alt="screenshot_3141" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/176c743c-3cae-40fe-9447-d97c2dc72680">
<img width="186" alt="screenshot_3142" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/5b9b01e7-80f0-49e6-8b2e-33288430b344">

All of the labels and StringDisplay instances currently use RichText -- a total of 8 RichText instances.  It was easier (and seemed more flexible while we were deciding on labels) to use the same type throughout.

3 of those RichText instances can be converted to Text:
* B label
* θ label
* θ StringDisplay

I'll add an option to StringDisplay for whether to use Text or RichText, since that will be generally useful.

**Comment by pixelzoom** [comment]
First, I'll note that this sim was performance tested on Chromebook and older iPad, and there was no problem noted with responsiveness.  That said...

**Comment by pixelzoom** [comment]
@samreid Can you describe how you measured the 9% time spent in FieldMeterNode readouts?  I'm having a difficult time trying to reproduce by looking at the the screenshot in https://github.com/phetsims/faradays-electromagnetic-lab/issues/142#issue-2211812769. And what is the console output that I see in that screenshot?  Did you add `console.log` to RichText, which might be contributing to the time spent?

**Comment by samreid** [comment]
I followed these steps:

1. Launch the simulation with no assertions. (Otherwise `assertSubtreeDisposed` swamps everything with a staggering 52%)
2. Open the bar magnet screen
3. Check the Field Meter checkbox
4. Dev Tools => Performance => start profiling
5. Drag the field meter back and forth rapidly

In following these steps again based on the code currently in main (with no console.log), I see around 18% time in `rebuildRichText`.

<img width="1719" alt="image" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/679486/f22871bf-31d4-448d-8866-762f3f7a7192">

If performance dragging the field meter back and forth on chromebook and older ipad is fine, this issue can likely be closed. I opened it because it seemed a bit laggy on my machine and thought it was worth taking a look.  There may not be much we can do if most/all the dynamic readouts have to be RichText.

**Comment by pixelzoom** [comment]
Thanks, those steps were helpful.  Following those steps, then switching to the "Bottom-Up" tab, I see 20.4% in `rebuildRichText`:

<img width="557" alt="screenshot_3149" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/8e416c40-871f-42d9-829e-d50bfc1cbddd">

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/commit/2282785d6b12ebfb31164f67bc67f97fc0b4083b, I added `StringDisplayOptions.useRichText`, which will be generally useful. 

Converting the 3 instances to Text that I identified in https://github.com/phetsims/faradays-electromagnetic-lab/issues/142#issuecomment-2026362427, I saw no performance improvement -- performance was actually a bit worse in all 4 tests that I performed, example below.

So I'm going to leave all of the labels and StringDisplays as RichText, for uniformity of implementation.

<img width="560" alt="screenshot_3151" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/6352aa1a-e092-4431-a99d-4487697523ad">

**Comment by pixelzoom** [comment]
Before I close this, I guess I should ask @jonathanolson to have a look, to see if there's any performance bottleneck in RichText that easily addressed.

**Comment by pixelzoom** [comment]
@jonathanolson Thoughts on this? Are there any peformance bottlenecks in RichText that could be improved?

**Comment by jonathanolson** [comment]
I'm a bit confused. I don't see how assertions are particularly relevant for performance testing, since they are stripped out of the built version. I never recommend performance testing unbuilt versions.

I used the steps in https://github.com/phetsims/faradays-electromagnetic-lab/issues/142#issuecomment-2027317665 to reproduce, using the normal `grunt --minify.mangle=false`.

![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/480878/085f8505-09ec-429f-a954-c35065622cbb)

I'm seeing that all of the RichText rebuild is taking 0.2ms per frame. This is 12% of the total, yes, but I'm not particularly concerned about it. If performance is 100x worse for RichText on older iPads, it could be possible to notice. Do we have performance reports of this being bad on older iPads?

More directly, RichText performance COULD be improved, especially if there are parts of the strings that are changing. This would be very complex code, and might take a week or two to improve to avoid the add/remove child. There's a chance it wouldn't improve by very much.

**Comment by pixelzoom** [comment]
Thanks @jonathanolson, that convinces me that there's nothing left to do here.  @samreid if this convinces you too, then please close. Otherwise suggest next steps.

**Comment by samreid** [comment]
I re-tested the performance of dragging the field meter node, and it is very snappy at the moment. I believe this issue can be closed.
