### ISSUE TITLE
FieldMeterNode says it can display 0 but cannot display 0

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#143]
During code review #103, we observed this code in FieldMeterNode.ts

```ts
/**
 * Converts a numeric gauss value to a RichText string in gauss, in decimal notation.
 * If the value is exactly zero, display '0' with no decimal places.
 */
function toGaussString( gauss: number, G: string ): string {
  if ( gauss < GAUSS_MIN_DISPLAY_VALUE ) {

    // Display '< 0.01' instead of '0.00', see https://github.com/phetsims/faradays-electromagnetic-lab/issues/84
    return StringUtils.fillIn( lessThanValueUnitsStringProperty, {
      value: `${GAUSS_MIN_DISPLAY_VALUE}`,
      units: G
    } );
  }
  else {
    const stringValue = ( gauss === 0 ) ? '0' : Utils.toFixed( gauss, GAUSS_DECIMAL_PLACES );
    return StringUtils.fillIn( valueUnitsStringProperty, {
      value: stringValue,
      units: G
    } );
  }
}
```

Note that it says it can display '0' but the first if statement prevents it from ever displaying 0.

**Comment by pixelzoom** [comment]
Good catch, this was a bug, introduced fairly recently.   For smally non-zero values, we want to display "< 0.01" instead of "0.00".   But the logic was missing the "non-zero" check, and the meter was displaying this for a 0G magnet:

<img width="210" alt="screenshot_3137" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/fc1d0b8d-20eb-4afb-b4b6-9921bfa222a8">

Fixing the logic in https://github.com/phetsims/faradays-electromagnetic-lab/commit/d5475f947e79176d80bfca1a0c784aaeced27128 results in the correct behavior for a 0G magnet:

<img width="236" alt="screenshot_3138" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/54d7852c-14d1-46bb-a6dd-7410e8259598">

Trivial change, so I'll go ahead and close. But feel free to have a look.
