### ISSUE TITLE
Home screen icon coil lump and gradient

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-electromagnetic-lab#148]
During code review #103, we observed that the home screen icon coils have a discontinuity "lump" near the top left (at point A) and an accentuated vertical gradient line (at point B). See this image that compares the home screen icon to the simulation version where there is less of a lump and less of a distracting vertical gradient line:

<img width="631" alt="image" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/679486/b66496c5-0ac8-4ce2-b6d9-a1a649638c2d">

**Comment by pixelzoom** [comment]
Good catch, we hadn't noticed this.

The problem was that the coil icons had much smaller radius than the actual coils in the sim, and the algorithm for creating the coils started to break down.  I fixed that in the above commit.

And I changed a couple of other things:
* For the Transformer screen, the electromagnetic coil should have a smaller diameter than the pickup coil, and look like it can pass through the pickup coil.
* For the both the Pickup Coil and Transformer screens, 3 loops for the pickup coil looks better to me (to fill up more horizontal space), despite the fact that 2 loops is the default setting in those screens.

Revised  icons are shown below.

@arouinfar please review these changes.  Let me know if you'd like to change anything. Or close if OK.

<img width="333" alt="screenshot_3140" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/d5362a84-5a4c-4c88-8607-d99bdbaf906e">

<img width="343" alt="screenshot_3139" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/698c3d85-f444-4842-9ceb-32006b476e76">

**Comment by arouinfar** [comment]
@pixelzoom the updates generally look good. 

> For the Transformer screen, the electromagnetic coil should have a smaller diameter than the pickup coil, and look like it can pass through the pickup coil.

I like this change! 

> For the both the Pickup Coil and Transformer screens, 3 loops for the pickup coil looks better to me (to fill up more horizontal space), despite the fact that 2 loops is the default setting in those screens.

I like 3 loops for the Pickup Coil screen. However, the Transformer screen should have a different number of loops in the coils because that's generally how transformers work. Maybe we can try 2 loops for the electromagnet and 4 loops for the pickup coil? Previously, it was the other way around, but if we are trying to fill up more space it may look better to give the pickup coil the larger number of loops.

**Comment by pixelzoom** [comment]
Here is 2 loops for the electromagnet and 4 loops for the pickup coil:


<img width="309" alt="screenshot_3156" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/9093b3d0-fc30-4461-9efe-0f8079b787c3">
<img width="971" alt="screenshot_3158" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/6a78878f-832b-48fd-9db6-caa2e193814a">


I think I like 3 loops for the electromagnet a bit better (committed to main):

<img width="311" alt="screenshot_3155" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/58f4c0a7-7f6e-4fb8-8b3c-779de5ee16d3">
<img width="970" alt="screenshot_3157" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/2f69a3b7-fda6-4d66-8071-d8776b368350">

Back to @arouinfar.  I could live with either of the above, if you prefer 2 loops for the electromagnet.

**Comment by pixelzoom** [comment]
@arouinfar and I looked at this when while triaging issues today, and she said that 3 loops for the electromagnet looked fine.

Closing.
