### ISSUE TITLE
Artifacts when moving coil [safari]

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#172]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1091, I see artifacts on the 3 screens where there is a moveable coil. The magnet, field meter, and compass don't produce any artifacts.

This doesn't occur with mac + chrome. 

**Steps to reproduce**
1. On screens 2-4 move a coil around. 

**Visuals**
<img width="424" alt="Screenshot 2024-06-01 at 9 33 13 AM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/56732529-8ac3-4f6c-b1d2-d0a768b15821">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Electromagnetic Lab‬
URL: https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.32/phet/faradays-electromagnetic-lab_all_phet.html
Version: 1.0.0-dev.32 2024-05-30 15:49:49 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Language: en-US
Window: 1317x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
It also happens on the Generator Screen when changing the Loop Area.

**Comment by Nancy-Salpepi** [comment]
This also occurs on the iPad (iPadOS 17.5.1)

**Comment by pixelzoom** [comment]
My first thought before reading the issue was that this was another "scenery artifact" problem, and we'd probably just live with it.  But now I see that it's really awful -- we need to do something about it.

In addition to MacBook Air M1 and iPad... This also occurs on my Intel MacBook Pro (MacBookPro16,1) with macOS 14.5 and Safari 17.5.  It occurs when dragging up, with pointer or keyboard, and by grabbing the foreground or background layer.

For example:

<img width="958" alt="screenshot_3349" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/8ae9f533-913e-4d9d-8e68-4fa48dc68816">

**Comment by pixelzoom** [comment]
I cannot reproduce this on iOS 17.5.1, so it seems specific to iPadOS.

Possibly related to:
* #188

**Comment by pixelzoom** [comment]
Running with `?webgl=false` does not resolve the problem.

**Comment by pixelzoom** [comment]
In 6/12/24 planning meeting...

@jonathanolson suggested adding a transparent rectangle that matches the correct bounds.

We also identified this bit of code in CurrentNode.ts as potentially relevant. It was added by @jonathanolson in https://github.com/phetsims/faradays-electromagnetic-lab/commit/9324117e5fa00e17c4ff39bd035faa69fc490941 to address electrons missing from screenshots.

```ts
export default class CurrentNode extends Sprites {
...
  public constructor( coilLayer: CoilLayer, coil: Coil ) {
...
    coil.coilSegmentsProperty.link( coilSegments => {
      const bounds = Bounds2.NOTHING.copy();

      for ( const coilSegment of coilSegments ) {
        coilSegment.expandBoundsToFit( bounds );
      }

      // Make sure the bounds are large enough to contain the SpriteInstances.
      bounds.dilate( FELConstants.CHARGED_PARTICLE_DIAMETER / 2 );

      this.canvasBounds = bounds;
    } );
```

**Comment by pixelzoom** [comment]
Assigning to @jonathanolson to review before our meeting on 6/14/24 @ 10AM MT.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/faradays-electromagnetic-lab/commit/ef8560ca251e3b0f1767453b6a909cdb3ccda74b for #188, I fixed the bounds of the interactive highlight for coils.  That fix unfortunately did not resolve this issue.

**Comment by pixelzoom** [comment]
@jonathanolson and I met about this issue. Notes:

We determined that the artifacts are due to the background layer of the coil.

We tried adding this to CoilNode, but it did not resolve the problem:

```ts
if ( platform.safari ) {
  this.boundsProperty.lazyLink( () => phet.joist?.display?.refreshSVG() );
}
```

We will probably need to add a transparent rectangle, sized to `localBoundsProperty` and dilated until the problem goes away. Add the rectangle `if ( platform.safari )`.

If transparent rectangle doesn't work, another approach to investigate is to use `getStrokedShape` to convert CoilSegmentNode to something that is fillable.

**Comment by pixelzoom** [comment]
The problem was resolved by adding a transparent rectangle to the coil's background layer when running on Safari. There is no workaround applied when running on other browsers.  I verified with Safari on macOS 14.5, iPadOS 17.5.1, and iOS 17.5.1.

@Nancy-Salpepi please verify with [1.0.0-dev.33](https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.33/phet/faradays-electromagnetic-lab_all_phet.html), close if OK.

**Comment by Nancy-Salpepi** [comment]
No artifacts in 1.0.0-dev.33! 
Tested with Safari + macOS 14.5 and iPadOS 17.5.1.

Closing!
