### ISSUE TITLE
Sim crashes on iPadOS 17.5.1

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#182]
**Test device**
iPad 9th generation

**Operating System**
iPadOS 17.5.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1091 the sim will crash after about 5 minutes of use. I will see this Message: 
>The webpage was reloaded because a problem occurred.  

When I tethered it to my mac, it just says that the webpage crashed. No other info appeared in the console. 
<img width="481" alt="Screenshot 2024-06-04 at 9 46 10 AM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/5b6b0843-fe64-458e-9271-67c33cc94484">

@KatieWoe and @matthew-blackman were also able to reproduce. 

I saw this a couple of times with the RC version of Greenhouse over the course of testing, but I am having a very hard time reproducing it. I tried a few other sims on main --PDL, Natural Selection, Molecule Shapes and didn't see the problem. 

It crashes really quickly if you add ?fuzz to the end of the url. 
It happens with both safari and chrome on the iPad. I am not able to reproduce on macOS 14.5.

**Steps to reproduce**
1. Add ?fuzz to the end of the url 

<details>

```
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Electromagnetic Lab‬
URL: https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.32/phet/faradays-electromagnetic-lab_all_phet.html
Version: 1.0.0-dev.32 2024-05-30 15:49:49 UTC
Features missing: applicationcache, applicationcache
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Language: en-US
Window: 810x977
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
```

</details>

**Comment by Nancy-Salpepi** [comment]
It happens pretty quickly when I move the battery on the Electromagnet Screen and then switch to the Transformer screen and try to move it there. Sometimes it crashes before the Transformer screen even opens.

https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/8978ce74-d0bc-4351-9139-a372bd3149cd

**Comment by KatieWoe** [comment]
I saw this with `?stringTest=X`. Before the crash many assets seemed to disappear, such as electrons, then whole coils. Seen on iPad

**Comment by pixelzoom** [comment]
One theory is that this may be related to Sprites and WebGL.

**Comment by pixelzoom** [comment]
Using the steps that @Nancy-Salpepi describes in https://github.com/phetsims/faradays-electromagnetic-lab/issues/182#issuecomment-2148100909...

Reproduced on my iPad6 with iPadOS 17.4.1. Also reproduced after updating to iPadOS 17.5.1.   As @Nancy-Salpepi also reported, no useful information when tethered.

Does NOT crash on iPhone 11 with iOS 17.5.1.  So this seems specific to iPadOS.

**Comment by pixelzoom** [comment]
@jonathanolson said that this seems indicative of a memory problem.  I should do a memory profile, and make sure that the heap size stays under 300 MB.

**Comment by pixelzoom** [comment]
I ran with `?brand=phet&ea&fuzz&debugger` and took heap snapshots at 1-minute intervals.  Heap size stabilizes at ~165MB, see below.  So we are well under 300 MB, and do not appear to have a memory leak.

<img width="177" alt="screenshot_3359" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/a3ebcb1f-3894-4fb1-b400-a6ce6665341f">

**Comment by pixelzoom** [comment]
The version tested is https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.32/phet/faradays-electromagnetic-lab_all_phet.html

Running with `?webgl=false` resolves the crash, so that points to a webgl problem.

Running with `?webgl=false` also shows that there is a problem with the renderer fallback for Sprites.  To improve rendering quality, the Node used to create the SpriteInstance is scaled up, then scaled down when the SpriteInstance is rendered. The inverse scaling part of the transform in ChargedParticleSpriteInstance `update` is apparently not being applied, so the electrons are huge -- see screenshot below.  Relevant code is in CurrentNode.ts -- see `RESOLUTION_SCALE = 8` and `class ChargedParticleSpriteInstance`.

@jonathanolson Could you please take a look at this?

![Screenshot 2024-06-12 at 2 33 07 PM](https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/4482b4bd-d64f-4200-be76-fca82ab1e407)

**Comment by pixelzoom** [comment]
The scaling problem with `?webgl=false` is apparently specific to iPadOS. It looks fine on macOS with Safari, Chrome, and Firefox.  It also looks fine on iOS 17.5.1.

**Comment by pixelzoom** [comment]
@jonathanolson and I met about this. Notes:

@jonathanolson does not have an iPad that's capable of running PhET sims, so I'll need to try several things and get back to him.

I tried running with a subset of screens, to see if the number of WebGL contexts is an issue.  The sim suns OK sometimes with smaller subsets of screens.  But (for example) `screens=1,2` crashed the first time, then ran OK the second time.  @jonathanolson hypothesized that we may be running out of GPU memory.  Not sure how to debug this.

- [x] Try fixing this in CurrentNode:

```diff
- this.transformType = SpriteInstanceTransformType.TRANSLATION;
+ this.transformType = SpriteInstanceTransformType.TRANSLATION_AND_SCALE;
```

- [x] Also consider this optimization in FieldNode, will not fix this problem, but is more correct:

```diff
- this.transformType = SpriteInstanceTransformType.AFFINE;
+ this.transformType = SpriteInstanceTransformType.TRANSLATION_AND_ROTATION;
```

- [x] Try turning off mipmap in CurrentNode:

```diff
-        mipmap: true,
-        mipmapBias: -0.7 // Use a negative value to increase the displayed resolution. See Imageable.setMipmapBias.
```

@jonathanolson suggested that tethering to XCode might provide some information. This is outside my wheelhouse, as I have no experience with XCode.

If none of the above works, we will likely need to use Canvas on iPadOS, and focus on fixing the Canvas fallback.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/faradays-electromagnetic-lab/commit/59267a3a560fcc1ef4e7b21f845247eab20ef811, I fixed the values of `transformType` for SpriteInstance.  That change is present in [1.0.0-dev.34](https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.34/phet/faradays-electromagnetic-lab_all_phet.html).  If does not fix the webgl crash, but it does fix the scaling problem noted in https://github.com/phetsims/faradays-electromagnetic-lab/issues/182#issuecomment-2163863201 when running with `?webgl=false`.  So this will allow us to run with the Canvas fallback on iPadOS if we cannot debug the webgl problem.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/faradays-electromagnetic-lab/commit/b6bd9f672d789982f4705a2e0ab10cb2bdd8e60c, I turned off mipmapping of the SpriteImage for electrons.  That change is present in https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.35/phet/faradays-electromagnetic-lab_all_phet.html.  This did not fix the problem, and the sim still crashed with webgl.  

I will revert https://github.com/phetsims/faradays-electromagnetic-lab/commit/b6bd9f672d789982f4705a2e0ab10cb2bdd8e60c.

**Comment by pixelzoom** [comment]
Discuss with @jonathanolson, after trying what we discuss this morning in https://github.com/phetsims/faradays-electromagnetic-lab/issues/182#issuecomment-2168465071.

We do not see any alternative other than to disable WebGL on mobile safari, because we're not getting any information when tethered, and have no way to debug this.  While the problem occurs on iPadOS and NOT on iOS, we have no way to detect which of those platforms we are on.  So WebGL will be disabled for both iPadOS and iOS, and the fallback of Canvas will be used. That has been implemented in https://github.com/phetsims/faradays-electromagnetic-lab/commit/07a4fef2faf283bd31f9fb8c541a83a9d37a3407, and published in (1.0.0-dev.36)[https://phet-dev.colorado.edu/html/faradays-electromagnetic-lab/1.0.0-dev.36/phet/faradays-electromagnetic-lab_all_phet.html].

@Nancy-Salpepi please review.  In addition to the crash, be on the lookout for any degradation of performance or rendering quality due to Canvas.

**Comment by kathy-phet** [comment]
> I saw this a couple of times with the RC version of Greenhouse over the course of testing, but I am having a very hard time reproducing it. I tried a few other sims on main --PDL, Natural Selection, Molecule Shapes and didn't see the problem.

@Nancy-Salpepi @KatieWoe - Given this statement, can you please test the published version of GHE with ?fuzz to see if it crashes and crashes quickly?

**Comment by Nancy-Salpepi** [comment]
@kathy-phet I fuzz tested published GHE with an iPad 9th generation, iPadOS 17.5.1 for 10 minutes and saw no crashes.

**Comment by Nancy-Salpepi** [comment]
@pixelzoom everything is looking and working nicely in dev.36. No crashes or issues with performance/rendering on iPad 9th generation  with iPadOS 17.5.1. 
I think this issue is good to close!
