### ISSUE TITLE
Please feature visibleProperty for dcPowerSupplyPanel and acPowerSupplyPanel

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#195]
For https://github.com/phetsims/qa/issues/1110

This item is listed in the examples.md and should be featured:

`faradaysElectromagneticLab.electromagnetScreen.view.dcPowerSupplyPanel.visibleProperty`

@arouinfar this isn't listed in the examples.md, but wondering if it should also be featured on the transformer screen (`faradaysElectromagneticLab.transformerScreen.view.dcPowerSupplyPanel.visibleProperty` )? Not sure if it would be part of a learning goal or not.

**Comment by KatieWoe** [comment]
I've also noticed that many of the visibleProperty elements seem to live in model, rather than view. This seems very odd to me. (Let me know if this should get it's own issue)

**Comment by KatieWoe** [comment]
Also, in a similar vein, the acPowerSupplyPanel visible property should probably be featured too.

**Comment by pixelzoom** [comment]
> I've also noticed that many of the visibleProperty elements seem to live in model, rather than view. This seems very odd to me. (Let me know if this should get it's own issue)

An issue will not be necessary, because this is intentional.

`visibleProperty` elements in the model include:

* compass.visibleProperty
* fieldMeter.visibleProperty
* barMagnet.fieldVisibleProperty
* electromagnet.fieldVisibleProperty

It is common practice to put `visibleProperty` in the model when it's relevant to the model.  In the above cases, `visibleProperty` is used as an optimization to decide whether to update the model element.  For example, if `compass.visibleProperty` is false, then there's no need to incurr the cost of updating the compass; and updates are deferred until it becomes visible.

**Comment by pixelzoom** [comment]
@arouinfar Let me know which of the `visibleProperty` instances mentioned above you would like to feature.

**Comment by arouinfar** [comment]
Good catch @Nancy-Salpepi. 

@pixelzoom please feature `dcPowerSupplyPanel.visibleProperty` and `acPowerSupplyPanel.visibleProperty` (all relevant screens).

**Comment by pixelzoom** [comment]
`dcPowerSupplyPanel.visibleProperty` and `acPowerSupplyPanel.visibleProperty` are now featured in the Electromagnet and Transformer screens.  @Nancy-Salpepi please review, close if OK.

**Comment by Nancy-Salpepi** [comment]
Both are featured on the Electromagnet and Transformer screens. Closing.
