### ISSUE TITLE
Overlapping Pointer Areas

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-electromagnetic-lab#201]
**Device**
MacBook Pro
**OS**
MacOS 14.5
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/qa/issues/1116
The pointer areas for some of the checkboxes (such as compass, field meter, and lock to axis) overlap slightly on all screens.
**Visuals**
![Screenshot 2024-07-25 at 12 12 03 PM](https://github.com/user-attachments/assets/76283f1f-b1ee-4614-8afb-61afa379db51)

**Comment by pixelzoom** [comment]
.... and in the Transformer screen:

<img width="741" alt="screenshot_3428" src="https://github.com/user-attachments/assets/47a4c834-06e1-4676-ba3a-673e596f431f">

**Comment by pixelzoom** [comment]
Primary fix is https://github.com/phetsims/faradays-electromagnetic-lab/commit/b8aac05f57bab78aed33970fe1d6a3a0e98fb189, the other commits are patches to release branches.

Note that the pointer area for the "Field Meter" checkbox is a bit taller than the other checkboxes in that panel, because it's icon is taller.  See screenshots below from the Bar Magnet and Transformer screens. 

@KatieWoe please review in master. If it looks OK, unassign yourself and change the status label to "status:fixed-awaiting-deploy".

<img width="344" alt="screenshot_3429" src="https://github.com/user-attachments/assets/4c248d7b-b054-4480-b6b9-f5225f60ea61">
<img width="344" alt="screenshot_3430" src="https://github.com/user-attachments/assets/ebf463d2-9d53-4530-8612-370fb7555b9c">

**Comment by KatieWoe** [comment]
Looks good on main

**Comment by pixelzoom** [comment]
To verify for https://github.com/phetsims/qa/issues/1128, https://github.com/phetsims/qa/issues/1129, https://github.com/phetsims/qa/issues/1130, and https://github.com/phetsims/qa/issues/1131...

Run the sim with `?showPointerAreas`.  Verify that pointer areas for checkboxes in the tools panel (lower right) do not overlap.

It is sufficient to test on 1 platform. Close this issue if everything looks OK.

**Comment by Nancy-Salpepi** [comment]
Looks fixed in rc2 for all sims in the suite!
