### ISSUE TITLE
Label on battery goes beyond orange end

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-electromagnetic-lab#202]
For https://github.com/phetsims/qa/issues/1116. If the string for the voltage label on the battery gets too long it goes off the orange end. If the voltage is negative it goes off the battery.
<img width="172" alt="toolong2" src="https://github.com/user-attachments/assets/bf8b710c-3d18-4b45-8d24-5691b3682dfd">
<img width="203" alt="toolong" src="https://github.com/user-attachments/assets/6621c76c-2968-4dac-82a7-c0581212a7c6">

**Comment by pixelzoom** [comment]
The commits above are a little odd, because I accidentally made the change with generator 1.0 checkout out (forgot to checkout main after a patch for a different issue).  https://github.com/phetsims/faradays-electromagnetic-lab/commit/20e24976fc9c74d7e160d6c900ae66ec74299244 is the primary commit, accidentally made in the "generator-1.0" branch of faradays-electromagnet-lab.  The other commits are patches to main and the other branches.  I patched all sims in the suite (including generator and magnet-and-compass) due to the weirdness of the primary commit.

**Comment by pixelzoom** [comment]
@KatieWoe thanks for finding this. Please review in master. If it looks OK, unassign yourself and change the status label to "status:fixed-awaiting-deploy".

Note that the copper end of the batter is now a little wider, so there's more room for the voltage value, and we can use a slightly larger font to improve readability. (I cleared this change with @arouinfar.)

<img width="200" alt="screenshot_3431" src="https://github.com/user-attachments/assets/44b0e9b2-acd0-43a5-9677-2fd6270d3c6f">
<img width="185" alt="screenshot_3432" src="https://github.com/user-attachments/assets/e46b9b14-bffb-498c-8280-91d5f676ea44">

**Comment by KatieWoe** [comment]
Looks good on main

**Comment by pixelzoom** [comment]
To verify this issue in https://github.com/phetsims/qa/issues/1128 and https://github.com/phetsims/qa/issues/1130...

Run the sim with `?stringTest=dynamic`.  Verify that the voltage display (e.g. '9 V') on the battery stays within the bounds of the copper section of the battery.  Test of the full range of positive and negative voltages.

It is sufficient to test this on 1 platform. Close this issue if everything is OK.

**Comment by Nancy-Salpepi** [comment]
Looks good in 1.0.0-rc.2 for FEL and for Magnets and Electromagnets. 
Closing.
