### ISSUE TITLE
Add interactive highlights for sim-specific draggable objects.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#53]
See [interactive-highlights-quickstart-guide.md](https://github.com/phetsims/phet-info/blob/main/doc/interactive-highlights-quickstart-guide.md).

**Comment by pixelzoom** [comment]
@arouinfar ready for review, close if OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom. 

The electromagnet and pickup coil appear to have an extra interactive highlight when mousing over the back portion of the coils, but otherwise things  are looking good on main. I do not see the extra highlight for keyboard focus, just interactive highlights with the mouse.
![Screen Shot 2024-01-17 at 8 53 08 AM](https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/859584d5-c7a0-481d-91bd-88776a334309)
![Screen Shot 2024-01-17 at 8 53 33 AM](https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/97ebb89f-2048-4a49-919b-6f9314d76f07)

**Comment by arouinfar** [comment]
Looks like the extra interactive highlight is indicative of bigger problems. I can move the back of the electromagnet coil with the mouse. I haven't been able to do the same for the pickup coil. 
![image](https://github.com/phetsims/faradays-electromagnetic-lab/assets/8419308/8d62317b-1b17-4591-8966-31e4db5eb594)

**Comment by pixelzoom** [comment]
> Looks like the extra interactive highlight is indicative of bigger problems. I can move the back of the electromagnet coil with the mouse. I haven't been able to do the same for the pickup coil.

Yes indeed, see https://github.com/phetsims/faradays-electromagnetic-lab/issues/56.

**Comment by pixelzoom** [comment]
I tried this change in CoilNode:

```diff
    this.backgroundNode = new FELMovableNode( coil, {
      hasKeyboardDragListener: false,
+     interactiveHighlightEnabled: false
```

... but then there is no interactive highlight for CoilNode when the pointer is over backgroundNode.

**Comment by pixelzoom** [comment]
@arouinfar and I discussed. The foreground and background are separate Nodes, and must be separate Nodes if the B-field and magnets are to "pass through" the coil.  Rather than try to make the foreground interactive highlight appear when over the background, we're going to live with 2 interactive highlights.  (We will have one focus rectangle, which is very doable and already implemented.
