### ISSUE TITLE
AC source looks odd with ?stringTest=dynamic

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/faradays-electromagnetic-lab#94]
**Test device**
MacBook Air M1 chip

**Operating System**
14.3.1

**Browser**
Safari 17.3.1

**Problem description**
For https://github.com/phetsims/qa/issues/1051, with ?stringTest=dynamic on the Electromagnet and Transformer Screens the graph in the AC source gets pushed to the right when the % is shown as a long string.

**Steps to reproduce**
1. add ?stringTest=dynamic to the end of the url
2. Go to the Electromagnet Screen and switch to AC source
3. Use the arrow keys to change the text

**Visuals**
<img width="706" alt="Screenshot 2024-03-01 at 3 19 17 PM" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/87318828/8727e6d4-6160-47df-8156-0e54304160a9">

**Comment by pixelzoom** [comment]
Good catch, missing a `maxWidth` for those number displays.  Fixed in the above commit, screenshot below.  Back to @Nancy-Salpepi to verify and close if OK.

<img width="330" alt="screenshot_3072" src="https://github.com/phetsims/faradays-electromagnetic-lab/assets/3046552/db8ad07e-e64c-4a15-94d8-8e6c09680e46">

**Comment by Nancy-Salpepi** [comment]
Looks good on main. Closing!
